COMPILE  := proc_config.vhd flashROM.vhd flashRAM.vhd mipsISA.vhd leftShifter.vhd signExtend.vhd adder_1bit.vhd alu_1bit.vhd aluCtrl.vhd mipsAlu.vhd mipsCtrl.vhd addrDecoder.vhd reg.vhd regFile.vhd bin2Char.vhd mipsCpu.vhd mipsCpu_ref.vhd mipsCpu_tb.vhd
SIMULATE := mipsCpu_tb

all: ghdl

-include ../../../tools/ghdl.mk
-include ../../../tools/gtkwave.mk
